Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace gaton.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace gaton.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace gaton.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


Pages/gato.cshtml.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace gaton.Pages
{
    public class GatoModel : PageModel
    {
        [TempData]
        public string tableroJson { get; set; } = "";

        [BindProperty]
        public int casillaSeleccionada { get; set; }

        [BindProperty]
        public string ganador { get; set; } = "";

        [BindProperty]
        public string turno { get; set; } = "X";

        public List<string> tablero { get; set; } = new();

        public void OnGet()
        {
            tablero = Enumerable.Repeat("", 9).ToList();
            turno = "X";
            tableroJson = JsonSerializer.Serialize(tablero);
        }

        public void OnPost()
        {
            if (string.IsNullOrEmpty(tableroJson))
            {
                tablero = Enumerable.Repeat("", 9).ToList();
            }
            else
            {
                tablero =
                    JsonSerializer.Deserialize<List<string>>(tableroJson)
                    ?? Enumerable.Repeat("", 9).ToList();
            }

            if (tablero[casillaSeleccionada] == "")
            {
                tablero[casillaSeleccionada] = turno;
                ganador = verificarGanador(tablero);

                if (string.IsNullOrEmpty(ganador))
                {
                    turno = turno == "X" ? "O" : "X";
                }
            }

            tableroJson = JsonSerializer.Serialize(tablero);
        }

        public string verificarGanador(List<string> tab)
        {
            int[][] jugadas = new int[][]
            {
                new[] { 0, 1, 2 },
                new[] { 3, 4, 5 },
                new[] { 6, 7, 8 },
                new[] { 0, 3, 6 },
                new[] { 1, 4, 7 },
                new[] { 2, 5, 8 },
                new[] { 0, 4, 8 },
                new[] { 2, 4, 6 },
            };

            foreach (var jGanadora in jugadas)
            {
                string a = tab[jGanadora[0]];
                string b = tab[jGanadora[1]];
                string c = tab[jGanadora[2]];

                if (!string.IsNullOrEmpty(a) && a == b && b == c)
                {
                    return a;
                }
                else if (
                    !string.IsNullOrEmpty(tab[0])
                    && !string.IsNullOrEmpty(tab[1])
                    && !string.IsNullOrEmpty(tab[2])
                    && !string.IsNullOrEmpty(tab[3])
                    && !string.IsNullOrEmpty(tab[4])
                    && !string.IsNullOrEmpty(tab[5])
                    && !string.IsNullOrEmpty(tab[6])
                    && !string.IsNullOrEmpty(tab[7])
                    && !string.IsNullOrEmpty(tab[8])
                )
                {
                    return "Empate";
                }
            }
            ;
            return "";
        }

        public IActionResult OnPostReiniciar()
        {
            tablero = Enumerable.Repeat("", 9).ToList();
            turno = "X";
            ganador = "";
            tableroJson = JsonSerializer.Serialize(tablero);

            return RedirectToPage();
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    
    <a class="btn btn-lg btn-outline-primary px-4 py-2 mb-4 fw-semibold" asp-page="/gato"></a>
        Visitar GATON 
    </a>


</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - gaton</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/gaton.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">gaton</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - gaton - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/gato.cshtml
@page
@model gaton.Pages.GatoModel
@{
    ViewData["Title"] = "Juego del Gato";
}
@if (!string.IsNullOrEmpty(Model.ganador))
{
    if(@Model.ganador == "X" || @Model.ganador == "O"){
    <h2>Gano: @Model.ganador</h2>
    }else{
        <h2>Fue: @Model.ganador</h2>
    }

}
else
{
    <h2>Turno: @Model.turno</h2>
}

<form method="post">
    <input type="hidden" name="Turno" value="@Model.turno" />
    <div class="tablero">
        @for (int i = 0; i < 9; i++)
        {
            <button type="submit" name="CasillaSeleccionada" value="@i" class="casilla">
                @Model.tablero[i]
            </button>
        }

    </div>
</form>

<form method="post" asp-page-handler="Reiniciar">
    <button class="reiniciar" type="submit">Reiniciar Juego</button>
</form>

<style>
    .tablero {
        display: grid;
        grid-template-columns: repeat(3, 100px);
        grid-template-rows: repeat(3, 100px);
        gap: 5px;
    }

    .casilla {
        background-color: #db5555;
        border: 2px solid #333;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 2.5rem;
        cursor: pointer;
    }

    .casilla:disabled {
        background-color: #a11313;
        cursor: default;
    }

    .casilla:hover:not(:disabled) {
        background-color: #e0e0e0;
    }
    
    .reiniciar{
        background-color: rgb(97, 141, 213);
        margin-top: 20px;
    }
</style>